name: E2E Tests

on: [ pull_request ]

env:
  REDIS_URL: 'redis://localhost:6379'
  REDIS_PASSWORD: ''

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NestJS API dependencies
        run: npm install
        working-directory: ./api

      - name: Build NestJS API
        run: npm run build
        working-directory: ./api

      - name: Start NestJS API
        run: npm start &
        working-directory: ./api

      - name: Test NestJS API
        run: |
          for i in {1..5}; do
            curl -f http://localhost:3000/api/redis/test && break
            echo "Retrying ($i)..."
            sleep 5
          done

      - name: Install React Client dependencies
        run: npm install
        working-directory: ./client

      - name: Build React Client
        run: npm run build
        working-directory: ./client

      - name: Serve React Client
        run: npm run dev &
        working-directory: ./client

      - name: Install Cypress dependencies
        run: npm install
        working-directory: ./cypress

      - name: Run Cypress Tests Now
        uses: cypress-io/github-action@v6
        with:
          start: echo "Starting Cypress Tests"
          wait-on: 'http://localhost:3000/api'
          wait-on-timeout: 60
          working-directory: ./cypress

      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
